import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { ConfigProvider } from "antd";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider
      theme={{
        components: {
          Dropdown: {
            colorPrimary: "#ff4a3b",
          },
        },
      }}
    >
      <html lang='en' className={`${GeistSans.variable}`}>
        <body>{children}</body>
      </html>
    </ConfigProvider>
  );
}
